import { Subject } from '@/types/study-material';

export const securityContent: Subject = {
  id: 'aws-subject-10',
  slug: 'security-compliance',
  title: 'Security, Compliance & Secrets',
  description: 'Protect systems & data',
  order: 10,
  chapters: [
    {
      id: 'aws-chapter-10-1',
      slug: 'kms',
      title: 'KMS',
      description: 'Key Management Service',
      order: 1,
      topics: [
        {
          id: 'aws-topic-10-1-1',
          slug: 'kms-overview',
          title: 'KMS Overview',
          description: 'Understanding encryption keys',
          content: `# AWS Key Management Service (KMS) Overview

## What is AWS KMS?

AWS Key Management Service (KMS) is a managed service that makes it easy for you to create and control the encryption keys used to encrypt your data. KMS is integrated with most other AWS services to help you protect your data.

## Key Concepts

### Customer Master Keys (CMKs)
- Primary encryption keys
- Created and managed in KMS
- Never leave AWS unencrypted
- Used to encrypt data keys

### Data Keys
- Symmetric keys used to encrypt data
- Generated by KMS
- Encrypted with CMKs
- Used within your applications

### Envelopes Encryption
 
- Data encrypted withAll data is encrypted.
- Data keys.
- Data  data
-  data

## KMS Components

### Keys
- Customer managed keys
- AWS managed keys
- AWS owned keys
- Import key material

### Aliases
- Friendly names for keys
- Simplify key management
- Rotate automatically
- Access control

### Key Policies
- Govern key usage
- IAM integration
- Resource-based policies
- Condition statements

### Grants
- Temporary permissions
- Specific operations
- Time-limited access
- Fine-grained control

## Key Types

### Symmetric CMKs
- Single encryption key
- Best performance
- Wide compatibility
- Most common use case

### Asymmetric CMKs
- Public/private key pairs
- Signing and encryption
- RSA and ECC algorithms
- Specialized use cases

### HMAC Keys
- Message authentication
- Integrity verification
- Hash-based authentication
- API authentication

## Key Management

### Creating Keys
- Choose key type
- Define usage
- Set rotation policy
- Configure permissions

### Key Rotation
- Automatic rotation
- Manual rotation
- Version management
.
- Back  version

### Key Deletion
- 7-30 day waiting period
- Irreversible action
- Dependency check
- Backup recommendations

### Key Import
- Bring your own keys
- Key material security
- Origin control
- Compliance requirements

## KMS Integrations

### Storage Services
- S3 encryption
- EBS encryption
- RDS encryption
- DynamoDB encryption

### Database Services
- Redshift encryption
- DocumentDB encryption
- Neptune encryption
- Aurora encryption

### Messaging Services
- SQS encryption
- SNS encryption
- Kinesis encryption
- Event

###
### Compute Services
- EC2 encryption
- Lambda environment variables
- ECS/EKS secrets
- Batch encryption

## Security Features

### IAM Integration
- Fine-grained permissions
- Resource-based policies
- Condition keys
- Cross-account access

### Audit Logging
- CloudTrail integration
- Key usage logging
- Administrative actions
- Compliance reporting

### Multi-Region Keys
- Same key in multiple regions
- Replicated keys
- Independent key material
- Regional isolation

### Custom Key Stores
- CloudHSM integration
- On-premise HSMs
- Key material control
- Regulatory compliance

## Pricing Model

### API Requests
- Generate, encrypt, decrypt
- Re-encrypt, describe
- Schedule key deletion
- Per request pricing

### Key Storage
- Per key per month
- Customer managed keys
- AWS managed keys (free)
- No charge for disabled keys

### Data Transfer
- Standard AWS rates
- Cross-region replication
- No additional KMS charges
- Network costs apply

## Best Practices

### Key Design
- Use least privilege
- Separate keys by data type
- Regular key rotation
- Document key usage

### Access Control
- Use IAM policies
- Implement key policies
- Monitor key usage
- Regular access reviews

### Key Management
- Enable automatic rotation
- Test key deletion
- Backup critical keys
- Document procedures

### Compliance
- Use appropriate key types
- Implement audit logging
- Document key lifecycle
- Regular compliance reviews

## Use Cases

### Data Encryption
- Database encryption
- File encryption
- Application data
- Backup encryption

### Secrets Management
- API keys
- Database credentials
- Configuration data
- Authentication tokens

### Compliance
- Regulatory requirements
- Data residency
- Industry standards
- Audit requirements

### Application Security
- Message encryption
- Digital signatures
- API authentication
- Data integrity

KMS provides a secure, scalable, and integrated solution for managing encryption keys across AWS services and applications. It's essential for data protection and compliance requirements.`,
          type: 'document',
          order: 1,
          tags: ['kms', 'encryption', 'security'],
          createdAt: '2024-01-01',
          updatedAt: '2024-01-01'
        }
      ],
      createdAt: '2024-01-01',
      updatedAt: '2024-01-01'
    }
  ],
  createdAt: '2024-01-01',
  updatedAt: '2024-01-01'
};
